project:
  type: website
  output-dir: docs

website:
  title: "Heinz Pampel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - presentations.qmd
      - working_groups.qmd
      - imprint.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

