---
title: "Presentations"
---

Genderjahn, S., Czerniak, A., Lange, M., & Pampel, H. (2025). Navigating the future of digital curation: The transformative role of persistent identifiers. 19th International Digital Curation Conference (IDCC), Dublin, Ireland, 18.02.2025. Slides: [PDF](https://doi.org/10.5281/zenodo.14889666).

Beucke, D., Meinecke, I., Severiens, T., Wrzesinski, M., Rothfritz, L., Pampel, H., & Vierkant, P. (2024). Vernetzt und Offen—Repositorien im Wandel. 25. Jahrestagung der Deutschen Initiative für Netzwerkinformation (DINI), Potsdam, 18.09.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.13851046).

Ferguson, L. M., Meistring, M., Pampel, H., & Strecker, D. (2024). Transparenz in der Wissenschaft: Strategien für offene Informationsversorgung. 25. Jahrestagung der Deutschen Initiative für Netzwerkinformation (DINI), Potsdam, 20.09.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.13837272).

Dalkilic, E., Fenner, M., König, M., Ochsner, C., Pampel, H., & Stockhausen, U. (2004). Blogs als Blaupause für das wissenschaftsgeleitete Open-Access-Publizieren. Open-Access-Tage 2024, Köln, 11.09.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.13819866).

Wrzesinski, M., Pampel, H., Rothfritz, L., & Khamis, C. O. (2024). Open-Access-Repositorien in Bewegung? Herausforderungen und Potentiale für institutionelle Repositorien in Deutschland. Open-Access-Tage 2024, Köln, 11.09.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.13773136).

Barbers, I., Kindling, M., Stadler, H., Strecker, D., Kaden, B., Mittermaier, B., & Pampel, H. (2024). Stand und Perspektive des Open-Access-Reportings. Open-Access-Tage 2024, Köln, 10.09.2024 Slides: [PDF](https://doi.org/10.5281/zenodo.13831942).

Ferguson, L. M., Pampel, H., & Meistring, M. (2024). Wissenschaftsgeleitetes Publizieren—Perspektiven für Forschungseinrichtungen. Open-Access-Tage 2024, Köln, 10.09.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.13789079).

Wrzesinski, M., Pampel, H., Rothfritz, L., & Khamis, C. O. (2024). Open-Access-Repositorien auf dem Prüfstand: Problemlagen und Strategien zur Professionalisierung. 112. BiblioCon, Hamburg, 06.06.2024. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-190741).

Meinecke, I., Severiens, T., Wrzesinski, M., Rothfritz, L., & Pampel, H. (2024). Szenarien für die Weiterentwicklung von Open-Access-Repositorien. 112. BiblioCon, Hamburg, 06.06.2024. Hands-on-Lab.

Session: Standards als Gemeinschaftsaufgabe 12. BiblioCon, Hamburg, 05.06.2016. Moderation.

Meistring, M., Ferguson, L. M., Pampel, H., & Bertelmann, R. (2024). Wissenschaftsgeleitete Publikationsinfrastrukturen: Chance für die Souveränität der Wissenschaft. 112. BiblioCon, Hamburg, 04.06.2024. Slides: [PDF](https://opus4.kobv.de/opus4-bib-info/frontdoor/index/index/docId/19115).

Wrzesinski, M., & Pampel, H. (2024). Pro OAR DE – Professionalisierung der Open-Access-Repositorien-Infrastruktur in Deutschland. Deutsche Initiative für Netzwerkinformation (DINI), Arbeitsgruppe Elektronisches Publizieren, Online, 19.04.2024. Slides: [PDF](https://doi.org/10.5281/zenodo.10998245).

Wrzesinski, M., & Pampel, H. (2024). Pro OAR DE – Professionalisierung der Open-Access-Repositorien-Infrastruktur in Deutschland. open-access.network Fokusgruppe Zeitveröffentlichung, Online, 11.04.2024. [PDF](https://doi.org/10.5281/zenodo.10998299).

Pampel, H., & Wrzesinski, M. (2024). Pro OAR DE – Professionalisierung der Open-Access-Repositorien-Infrastruktur in Deutschland. open-access.network Fokusgruppe Fachrepositorien, Online, 06.03.2024. Poster. [PDF](https://doi.org/10.5281/zenodo.10784982).

Pampel, H., Weisweiler, N. L., Strecker, D., Witt, M., Vierkant, P., Elger, K., Bertelmann, R., Buys, M., Ferguson, L. M., Kindling, M., Kotarski, R., & Petras, V. (2024). re3data – Indexing the Global Research Data Repository Landscape Since 2012. 18th International Digital Curation Conference (IDCC24), Edinburgh, Scotland, 20.02.2024. Poster: [PDF](https://doi.org/10.5281/zenodo.10620717)

Pampel, H., Weisweiler, N. L., Strecker, D., Witt, M., Vierkant, P., Elger, K., Bertelmann, R., Buys, M., Ferguson, L. M., Kindling, M., Kotarski, R., & Petras, V. (2024). re3data—Indexing the global research data repository landscape since 2012. RDA Deutschland Tagung 2024 (RDA-DE 2024), Potsdam, 20.02.2024. Poster: [PDF](https://doi.org/10.5281/zenodo.10624171).

Panel Discussion: ChatGPT, DeepL und Co. als akademische Hilfsmittel: Brauchen wir in der Zukunft KI-Literacy und Tool-Transparency? 17th Internationales Symposium für Informationswissenschaft. Chur, Schweiz, 07.11.2023.

Burger, F., Czerniak, A., Fischer, B., Glagla-Dietz, S., Messerschmidt, L., Pampel, H., Schirrwagen, J., Schrader, A. C., Vierkant, P., & Ziedorn, F.(2023). PID Network Germany – Vision of a Networked and Open Scientific Landscape. International Data Week 2023. Salzburg, 24.10.2023. Poster: [PDF](https://doi.org/10.5281/zenodo.10014364).

Panel Discussion: Open Access in der Region Berlin-Brandenburg: Was wurde erreicht und wo geht es hin? Zuse Institut Berlin, 24.10.2023.

Pampel, H. (2023). Impuls: Kriterien für Verträge mit Publikationsdienstleistern. Transform2Open Stakeholder Workshop. Online, 16.10.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.10036924).

Meistring, M., Barbers, I., Ferguson, L. M., Höhnow, T., Pampel, H., Schön, M., Shelly, J., Bertelmann, R., Kostädt, P., & Mittermaier, B. (2023). Budgets, Kriterien und Kompetenzen – die finanziellen Dimensionen der Open-Access-Transformation gestalten. Open-Access-Tage 2023. Berlin, 29.09.2023. Slides: [PDF](http://doi.org/10.5281/zenodo.8389703).

Fenner, M., & Pampel, H. (2023). Making scholarly blogs permanently accessible. Open-Access-Tage 2023. Berlin, 28.09.2023. Poster: [PDF](https://doi.org/10.5281/zenodo.8290081).

Burger, F., Czerniak, A., Fischer, B., Glagla-Dietz, S., Messerschmidt, L., Pampel, H., Schirrwagen, J., Schrader, A., Vierkant, P., & Ziedorn, F. (2023). PID Network Deutschland – Vision einer vernetzten und offenen Wissenschaftslandschaft. Open-Access-Tage 2023. Berlin, 28.09.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.8210580).

Pampel, H. (2023). Diskussion der Thesen zur Zukunft des wissenschaftsgeleiteten Open- Access-Publizierens. Konferenz Wissenschaftsgeleitetes Open-Access-Publizieren. Berlin. 26.09.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.8388753).

Ferguson, L. M., Schrader, A. C., Bertelmann, R., Bruch, C., Genderjahn, S., Meistring, M., Messerschmidt, L., Pampel, H., Schultze-Motel, P., & Weisweiler, N. (2023). Open Science & Reproducibility. Helmholtz Incubator Summer Academy. Online, 18.09.2023. Slides: [PDF](https://events.hifis.net/event/858/contributions/5474/attachments/1382/2493/2023-09-18_Incubator-Summer-Academy_Schrader.pdf).

Ferguson, L. M., Pampel, H., Bertelmann, R., Meistring, M., & Weisweiler, N. (2023). Helmholtz Open Science Policy—Implementing the UNESCO Recommendation on Open Science. OAI – The Geneva Workshop on Innovations in Scholarly Communication (OAI13). Online, 07.09.2023, Slides: [PDF](https://doi.org/10.5281/zenodo.8307743).

Weisweiler, N. L., Elger, K., Pampel, H., Axtmann, A., Bertelmann, R., Nguyen Thanh, B., Schnepf, E., Petras, V., Semrau, A., Strecker, D., Ulrich, R., Upmeier, A., Vierkant, P., Weickert, G., & Witt, M. (2023). Strengthening Open Science Practices Through re3data, the Global Registry of Research Data Repositories. GeoBerlin 2023, 150th PGLA (BGR) Anniversary and 175th DGGV Anniversary. Berlin, 04.09.2023.

Messerschmidt, L., Schrader, A. C., Steinbach, P., Ferguson, L. M., & Pampel, H. (2023). Why Openness and Reproducibility in Machine Learning Matter. Helmholtz AI Conference 2023, Hamburg, 14.06.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.8064132).

Rothfritz, L., & Pampel, H. (2023). Edit-a-thon: Diversität in Wikipedia-Beiträgen zur Bibliotheks- und Informationswissenschaft. ECDF Gender & Diversity Network. Berlin, 31.05.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.7990560).

Höhnow, T., Shelly, J., Barbers, I., Bertelmann, R., Ferguson, L. M., Kostädt, P., Meistring, M., Mittermaier, B., Pampel, H., & Schön, M. (2023). Stellenprofile in der Open-Access-Administration. 111. BiblioCon. Hannover, 24.05.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.8032206).

Schrader, A., Bertelmann, R., Pampel, H., & Vierkant, P. (2023). PID Network Deutschland – Auf dem Weg zu einer PID-Roadmap für Deutschland. 111. BiblioCon. Hannover, 24.05.2023. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-184242).

Ferguson, L. M., Schön, M., Barbers, I., Bertelmann, R., Höhnow, T., Kostädt, P., Meistring, M., Mittermaier, B., Pampel, H., & Shelly, J. Transform2Open—Vernetzung in der Open-Access-Transformation. 111. BiblioCon. Hannover, 24.05.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.8004357).

Pampel, H. (2023). Open Science at a Research Performing Organization. Leibniz-Institut für Ost- und Südosteuropaforschung. Online, 22.05.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.7961700).

Schön, M., Barbers, I., Bertelmann, R., Ferguson, L. M., Höhnow, T., Kostädt, P., Meistring, M., Mittermaier, B., Pampel, H., & Shelly, J. (2023). Kostenmonitoring—Problemfelder und Handlungsbedarfe. Workshop Kostenmonitoring – Problemfelder und Handlungsbedarf, Online, 11.05.2023. [Slides](https://doi.org/10.5281/zenodo.7993722).

Pampel, H. (2023). Informationsinfrastrukturen für Open Science. Berliner Bibliothekswissenschaftliches Kolloquium (BBK) des Institut für Bibliotheks- und Informationswissenschaft der Humboldt-Universität zu Berlin. Berlin, 09.05.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.7915487).

Panel Discussion: Berlin goes Open Research? Freien Universität Berlin. Berlin, 04.05.2023.

Pampel, H., & Bertelmann, R. (2023). Policies and networking for the sustainable handling of research software at Helmholtz. deRSE23, Heinz Nixdorf MuseumsForum, Paderborn, 21.02.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.7661286).

Pampel, H. (2023). Vernetzte und offene Wissenschaft: PIDs für Open Science. RDA DE Tagung. Online, 16.02.2023. Slides: [PDF](https://doi.org/10.5281/zenodo.7645554).

Pampel, H. (2022). Informationsbudget — Hintergrund und Konzept und Umsetzungsstrategien. Workshop Informationsbudget der Leibniz-Gemeinschaft. Berlin, 15.11.2022. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5013949).

Panel Discussion: Digitaler Salon: Wissen macht Klima. Alexander von Humboldt Institut für Internet und Gesellschaft. Berlin, 26.10.2022.

Höhnow, T., Pampel, H. (2022). Transform2Open. Cost monitoring, criteria, competencies, and processes of the Open Access transformation. openCost Expert Workshop. DESY. Hamburg, 06.10.2022. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5013387).

Pampel, H. (2022). Open Access kommunizieren. Strategien und Erfahrungen. Workshop „Open Access kommunizieren“ der Vernetzungs- und Kompetenzstelle Open Access Brandenburg. Online, 06.10.2022. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/open-access-kommunizieren-strategien-und-erfahrungen), [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5013385).

Schrader, A., Bertelmann, R., Bruch, C., Ferguson, L. M., Pampel, H., Schultze-Motel, P., & Weisweiler, N. L. (2022). Enabling Open Science practices in Helmholtz! Helmholtz Metadata Collaboration (HMC) Conference 2022. Online, 05.-06.10.2022. Poster: [PDF](https://doi.org/10.5281/zenodo.7120472).

Schrader, A., Pampel, H. (2022). ORCID in Germany—A project-driven success story. Collaboration (HMC) Conference 2022. Online, 05.-06.10.2022. Poster: [PDF](https://doi.org/10.5281/zenodo.7120694).

Schirrwagen, J., Schrader, A., & Pampel, H. (2022). Persistent Identifier in Open-Access-Publikationsworkflows. Open-Access-Tage 2022. Bern, 21.09.2022. Slides: [PDF](https://doi.org/10.5281/zenodo.7118359).

Pampel, H. (2022). Research Data Management as a prerequisite for Open Research Data at Helmholtz. Workshop Forschungsdatenmanagement in der Max-Planck-Gesellschaft. Online, 14.09.2022. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/research-data-management-as-a-prerequisite-for-open-research-data-at-helmholtz), [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5013231).

Pampel, H. (2022). Informationsbudget — Hintergrund und Konzept. Helmholtz Open Science Forum Publikationskostenmanagement. Online, 14.09.2022. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5013229).

Schrader, A.; Pampel, H.; Vierkant, P. (2022). Vernetzte und offene Wissenschaft: PIDs für Open Science. 8. Bibliothekskongress. Leipzig, 31.05.2022. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-179132).

Pampel, H. (2022). Informationsbudget — Hintergrund und Konzept. Workshop „Budgetentwicklung im Kontext der Open-Access-Transformation“. Online, 18.05.2022. Slides: [PDF](https://doi.org/10.5281/zenodo.6575953).

Pampel, H. (2022). Informationsbudget — Hintergrund und Konzept. Workshop „Budgetentwicklung im Kontext der Open-Access-Transformation“. Online, 13.05.2022. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5011384).

Pampel, H. (2022). Open Science und Transfer. Helmholtz Open Science Forum „Open Science und Transfer“. Online, 12.05.2022. [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5011343).

Pampel, H. (2022). Informationsbudget — Hintergrund und Konzept. Workshop „Budgetentwicklung im Kontext der Open-Access-Transformation“. Online, 26.04.2022. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/informationsbudget-hintergrund-und-konzeptpdf), [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5011222).

Boltze, J.; Pampel, H.; Putnings, M. (2021). DeepGreen - Vom Projekt zum nationalen Open-Access-Service. Open-Access-Tage 2021. Online, 29.09.2021. Slides: [PDF](https://doi.org/10.5281/zenodo.5529724).

Session: Aktuelles von den Forschungsförderern: OA-Programme und -Monitorings. Open-Access-Tage 2021. Online, 27.09.2021. Moderation.

Weisweiler, N. L.; Elger, K.; Ferguson, L. M.; Kindling, M.; Nguyen, T. B.; Pampel, H.; Schabinger, R.; Schnepf, E.; Semrau, A.; Strecker, D.; Trofimenko, M.; Ulrich, R.; Vierkant, P.; Wang, Y.; Witt, M.; Bertelmann, R.; Cousijn, H.; Petras, V.; Upmeier, A. (2021). re3data COREF – Developing a Conceptual Model for User Stories for the Registry of Research Data Repositories. Open Science Fair 2021 (OSFAIR2021). Online, 23.09.2021. Slides: [PDF](https://doi.org/10.5281/zenodo.5529651).

Weisweiler, N.; Bertelmann, R.; Elger, K.; Ferguson, L. M.; Goebelbecker, H.-J.; Kindling, M.; Kloska, G., Nguyen, T. B.; Pampel, H.; Petras, V.; Schabinger, R.; Schnepf, E.; Semrau, A.; Strecker, D.; Trofimenko, M.; Ulrich, R.; Vierkant, P.; Wang, Y.; Witt, M. (2021). re3data COREF - Ausbau und Weiterentwicklung des Registry of Research Data Repositories. 109. Deutscher Bibliothekartag. Bremen, 18.06.2021. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-177132).

Ferguson, L. M.; Weisweiler, N. L.; Pampel, H.; Bertelmann, R.; Schrader, A.: Gute wissenschaftliche Praxis und Open Science: Zur Rolle der Bibliotheken im DFG-Kodex. 109. Deutscher Bibliothekartag. Bremen, 18.06.2021. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-177233).

Pampel, H.: ORCID DE – Stand und Perspektive 2021. 5. ORCID DE Workshop. Online. 02.06.2021. Slides: [PDF](http://doi.org/10.5281/zenodo.4893768).

Boltze, J.; Groß, M.; Lohrum, S.; Pampel, H.; Putnings, M.; Retter, R.; Rusch, B.; Schäffler, H.; Söllner, K.: Kick-Off für die Zukunft von DeepGreen: Bisherige Erfolge und neue Ziele. DeepGreen Workshop. Online, 02.03.2021. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5005945).

Pampel, H.: ORCID DE – Stand des Projektes und aktuelle Aktivitäten im Bereich Organization Identifiers. 4. ORCID DE Workshop. Online, 04.12.2020. Slides: [PDF](http://doi.org/10.5281/zenodo.4305432).

Schrader, A.; Pampel, H.: ORCID DE – Identifikation von Forschenden im Kontext des Kerndatensatz Forschung. Workshop "Fünf Jahre Kerndatensatz Forschung im deutschen Wissenschaftssystem". Online, 10.11.2020. Slides: [PDF](http://doi.org/10.5281/zenodo.4292629).

Schrader, A.; Pampel, H.: ORCID für Förderer. Online, 16.11.2020. Slides: [PDF](http://10.0.20.161/zenodo.4275273).

Schrader, A.; Pampel, H.: ORCID DE – Stand und Perspektive. 2. ORCID DE Webinar. Online, 07.10.2020. Slides: [PDF](http://doi.org/10.5281/zenodo.4071769).

Pampel, H.; Schrader, A.: ORCID DE – Stand und Perspektive 2020. ORCID DE Webinar. Online, 01.07.2020. Slides: [PDF](https://doi.org/10.5281/zenodo.3925551).

Pampel, H.: Leitlinien zur Sicherung guter wissenschaftlicher Praxis – Handlungsoptionen für Bibliotheken. Sitzung des AK Bibliotheks- und Informationsmanagement der Helmholtz-Gemeinschaft. Online, 18.03.2020. Slides: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5001464).

Pampel, H., Bertelmann, R., Vierkant, P.: Helmholtz Open Science Office - Shaping the PID Landscape in Germany and Beyond. RDA Deutschland Tagung 2020. Potsdam, 27.-29.02.2020. Poster: [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_5000933).

Strecker, D.; Pampel, H.: Fachgesellschaften und Open Access in Deutschland – eine Analyse zur Herausgabe von Zeitschriften. OA2020 DE Workshop. Georg-August-Universität Göttingen, 04.11.2019. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/fachgesellschaften-und-open-accessindeutschlandeine-analysezur-herausgabevon-zeitschriften), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:4751889).

Pampel, H.: Open Access an wissenschaftlichen Einrichtungen in Deutschland – Ergebnisse einer Erhebung im Jahr 2018. Leibniz-Gemeinschaft, AK Open Science. Berlin, 23.10.2019. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/open-access-an-wissenschaftlichen-einrichtungen-in-deutschland-ergebnisse-einer-erhebung-im-jahr-2018), [PDF](https://gfzpublic.gfz-potsdam.de/pubman/item/item_4768888).

Vierkant, P., Pampel, H., Ulrich, R., Scholze, F., Kindling, M., Witt, M., Elger, K.: re3data COREF - Community Driven Open Reference for Research Data Repositories. 20. DINI-Jahrestagung. Osnabrück, 08.10.2019. Poster: [PDF](https://doi.org/10.5281/zenodo.3565478).

Vierkant, P., Pampel, H., Dreyer, B., Glagla-Dietz, S., Pietsch, C., Summann, F., Schirrwagen, J.: Praxis im ORCID Deutschland Konsortium. 20. DINI-Jahrestagung. Osnabrück, 08.10.2019. Slides: [PDF](https://doi.org/10.5281/zenodo.3564495).

Pampel, H.: Open Access an wissenschaftlichen Einrichtungen in Deutschland – Ergebnisse einer Erhebung im Jahr 2018. Open-Access-Tage 2019. Leibniz Universität Hannover, 01.10.2019. Slides: [PDF](https://doi.org/10.5281/zenodo.3468522).

Strecker, D.; Pampel, H.: Fachgesellschaften und Open Access in Deutschland – eine Analyse zur Herausgabe von Zeitschriften. Open-Access-Tage 2019. Leibniz Universität Hannover, 01.10.2019. Slides: [PDF](https://doi.org/10.5281/zenodo.3406288).

Vierkant, P.; Pampel, H.; Dreyer, B., Glagla-Dietz, S.; Hartmann, S.; Pietsch, C.; Summann, F.; Schirrwagen, J.: Praxis im ORCID Deutschland Konsortium. Open-Access-Tage 2019. Leibniz Universität Hannover, 01.10.2019. Poster: [PDF](https://doi.org/10.5281/zenodo.3448225).

Scholze, F.; Vierkant, P.; Pampel, H.; Ulrich, R.; Kindling, M.; Witt, M.; Elger, K.: re3data - Open infrastructure for Open Science. OAI 11 – The CERN-UNIGE Workshop on Innovations in Scholarly Communication. University of Geneva, Schweiz, 19.06.2019. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:4323892).

Wannick, E.; Boltze, J.; Dierkes, T.; Pampel, H.; Putnings, M.: DeepGreen – Pushing on the Green Road of Open Access. Open Repositories 2019. Universität Hamburg, 12.06.2019. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:4348894).

Vierkant, P.; Pampel, H.; Ulrich, R.; Scholze, F.; Kindling, M.; Witt, M.; Elger, K.: re3data - Open infrastructure for Open Science. Open Repositories 2019. Universität Hamburg, 11.06.2019. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:4323890).

Vierkant, P.; Pampel, H.; Dreyer, B.; Glagla-Dietz, S.; Hartmann, S.; Pietsch, C.; Summann, F.; Schirrwagen, J.: ORCID Germany Consortium - supported by the ORCID DE project. Open Repositories 2019. Universität Hamburg, 11.06.2019.Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:4315904).

Vierkant, P.; Pampel, H.; Bertelmann, R.; Dreyer, B.; Strecker, D.; Summann, F.;Hartmann, S.: ORCID Germany Consortium - supported by the ORCID DE project. 2019 ORCID Consortia Workshop, Atlanta, USA, 20-22.05.2019. Poster: [PDF](http://doi.org/10.5281/zenodo.3234439).

Pampel, H.: Open-Access-Strategie für Brandenburg – ein Impuls.„Intensivworkshop Open-Access-Strategie Brandenburg“. Fachhochschule Potsdam, 10.12.2018. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/openaccessstrategie-fr-brandenburg-ein-impuls).

Pampel, H.: Forschungsdaten-Repositorien. Vorlesung. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 29.11.2018. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/forschungsdatenrepositorien-124386291).

Pampel, H.:Ausblick: DOI, ORCID, ORG ID et al. – PIDs für Informationsobjekte im Kontext von Open Science. 3. ORCID DE Workshop. Universität Bielefeld, 08.11.2018. Slides: [Slideshare,](https://www.slideshare.net/heinzpampel/ausblick-pids-fr-informationsobjekte-im-kontext-von-open-science) [PDF](http://doi.org/10.5281/zenodo.1484150).

Vierkant, P.; Pampel, H.; Bertelmann, R.; Dreyer, B.: ORCID Germany Consortium - Numbers and Figures. Universität Bielefeld, 08.11.2018. Poster: [PDF](http://doi.org/10.5281/zenodo.1483737).

Vierkant, P., Pampel, H., Müller, U.: ORCID DE - Zwei Projektjahre. ORCID DE Workshop. Universität Bielefeld, 08.11.2018. Poster: [PDF](http://doi.org/10.5281/zenodo.1483655).

Vierkant, P., Pampel, H.: Open Science in der Helmholtz-Gemeinschaft. 19. Jahrestagung der Deutschen Initiative für Netzwerkinformation (DINI). Universität Bielefeld, 07.11.2018. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:3660899).

Pampel, H.: "Open-Access-Transformation" in der Helmholtz-Gemeinschaft. OA2020-DE Workshop. Universität Bielefeld, 18.11.2018. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/openaccesstransformation-in-der-helmholtzgemeinschaft), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:3613889:2).

Vierkant, P.; Pampel, H.; Elger, K.; Kindling, M.; Ulrich, R.; Witt, M.; Fenner, M.: Status quo and perspective of re3data. MERIL-2 Interoperability Workshop. Athen, 25.06.2018. Slides: [PDF](http://doi.org/10.5281/zenodo.1297432).

Vierkant, P.; Pampel, H.: ORCID DE - Autorenidentifikation mit ORCID in Deutschland. 107. Deutscher Bibliothekartag. Berlin, 13.06.2018. Slides: [PDF](https://nbn-resolving.org/urn:nbn:de:0290-opus4-36543).

Vierkant, P.; Pampel, H.; Bertelmann, R.; Dreyer, B.: ORCID Germany Consortium - Numbers and Figures. 2018 ORCID Consortium Workshop.Lissabon, 17.01.2018. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:2956904).

Pampel, H.: Forschungsdaten-Repositorien. Vorlesung. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 04.12.2017. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:3139895).

Vierkant, P.; Pampel, H.; Bertelmann, R.; Hartmann, S.; Summann, F.; Pieper, D.; Pietsch, C.; Müller, U.; Fenner, M.: ORCID DE - das erste Projektjahr. Open Access in Berlin/Brandenburg. Berlin, 26.10.2017. Poster: [PDF](http://doi.org/10.5281/zenodo.1026879).

Pampel, H.: ORCID DE – Autorenidentifikation, Publikationsmanagement und Open Science. Vorlesung. Fachhochschule Potsdam, 24.10.2017. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/orcid-de-autorenidentifikation-publikationsmanagement-und-open-science), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:3139897).

Vierkant, P.; Pampel, H.; Bertelmann, R.; Hartmann, S.; Summann, F.; Pieper, D.; Pietsch, C.; Müller, U.; Fenner, M.: ORCID DE - Förderung der Open Researcher and Contributor ID in Deutschland. Open-Access-Tage 2017. Dresden, 12.09.2017. Poster: [PDF](https://doi.org/10.5281/zenodo.887536).

Pampel, H.: ORCID DE – Stand des Projektes. 2. ORCID DE Workshop. Frankfurt am Main, 07.09.2017. Slides: [Slideshare](https://www.slideshare.net/heinzpampel/orcid-de-stand-des-projektes),[PDF](https://doi.org/10.5281/zenodo.889302).

Pampel, H.: ORCID DE – Stand und Perspektive. 106. Deutscher Bibliothekartag. Frankfurt am Main, 01.06.2017. Slides:[Slideshare](https://www.slideshare.net/heinzpampel/orcid-de-stand-und-perspektive), [PDF](http://nbn-resolving.de/urn/resolver.pl?urn:nbn:de:0290-opus4-29687).

Fritzsch, B.; Bernstein, E.; zu Castell, W.; Diesmann, M.; Haas, H., Hammitzsch, M.; Konrad, U.; Lähnemann, D.; McHardy, A.; Pampel, H.; Scheliga, K. S.; Schreiber, A.; Steglich, D.: Scientific Software – the role of best practices and recommendations. EGU General Assembly 2017. Vienna, 28.04.2017. (Geophysical Research Abstracts, Vol. 19, EGU2017-3294, 2017.) Abstract: [PDF](http://meetingorganizer.copernicus.org/EGU2017/EGU2017-3294.pdf).

Pampel, H.: Forschungsdatenmanagement. Seminar im Kontaktstudium Bibliotheks- und Informationsmanagement. Hochschule der Medien (HdM). Stuttgart, 09.03.2017.

Pampel, H.: ORCID in Deutschland - Stand und Perspektive. Workshop "Der Kerndatensatz Forschung - und nun?". Berlin, 21.02.2017. Slides: [PDF](https://doi.org/10.5281/zenodo.375656), [Slideshare](https://www.slideshare.net/heinzpampel/orcid-in-deutschland-stand-und-perspektive).

Elger, K.; Pampel, H.; Vierkant, P; Witt, M.: New Features of the re3data Registry of Research Data Repositories. AGU Fall Meeting. San Francisco, 15.12.2016. [Abstract](https://agu.confex.com/agu/fm16/meetingapp.cgi/Paper/143463).

Pampel, H.: Forschungsdaten-Repositorien. Vorlesung. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 07.12.2016.

Vierkant, P. & Pampel, H.: ORCID DE – Initiative zur Förderung von ORCID in Deutschland. RDA-Deutschland-Treffen 2016. Potsdam, 28.11.2016. Slides: [PDF](http://os.helmholtz.de/fileadmin/user_upload/os.helmholtz.de/Workshops/rda_de_16_vierkant.pdf).

Pampel, H.: ORCID DE – Initiative zur Förderung von ORCID in Deutschland. Herbsttagung der Bibliotheken in der Chemisch-Physikalisch-Technische Sektion der Max-Planck-Gesellschaft. Potsdam, 10.11.2016. Slides: [Slideshare](http://www.slideshare.net/heinzpampel/orcid-de-initiative-zur-frderung-von-orcid-in-deutschland-68585593).

Panel Discussion: Open Access an der Fachhochschule Potsdam. Fachhochschule Potsdam. 02.11.2018. [Diskussion](https://oaatfhp.jimdo.com/).

Panel Discussion: Open in Action - Praxisperspektiven. Wikimedia Deutschland. Berlin, 26.10.2016. [Diskussion](http://www.fu-berlin.de/sites/open_access/Veranstaltungen/oa-week-2016-ausstellung/index.html).

Pampel, H.: ORCID DE und (datenschutz-) rechtliche Fragestellungen. ORCID DE Outreach Workshop. Potsdam, 25.10.2016. Slides: [PDF](http://doi.org/10.5281/zenodo.163471).

Pampel, H.: ORCID DE – Ausblick. ORCID DE Outreach Workshop. Potsdam, 25.10.2016. Slides: [PDF](http://doi.org/10.5281/zenodo.163383).

Vierkant, H.; Pampel, H.; Bertelmann, R.; Hartmann, S.; Summann, F.; Pieper, D.; Müller, U.; Fenner, M.; Schirrwagen, J.; Jahn, N.: ORCID DE. Posterausstellung "Open in Action" zur Open Access Week 2016. Berlin, 24.10.-28.10.2016. Poster: [PDF](https://rs.cms.hu-berlin.de/open-access-week/?r=23).

Pampel, H.: ORCID DE – Stand und Perspektive von ORCID in Deutschland. 33. Arbeitstagung Bibliotheks- und Informationswesen der Fraunhofer-Gesellschaft. Hamburg, 13.10.2016. Slides: [Slideshare](http://www.slideshare.net/heinzpampel/orcid-de-stand-und-perspektive-von-orcid-in-deutschland), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1776896).

Pampel, H.: ORCID DE – Initiative zur Förderung von ORCID in Deutschland. 17. Jahrestagung des AK Bibliotheken und Informationseinrichtungen der Leibniz-Gemeinschaft. Mannheim, 15.09.2016. Slides: [Slideshare](http://www.slideshare.net/heinzpampel/orcid-de-initiative-zur-frderung-von-orcid-in-deutschland-66050942), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1720891).

Witt, M.; Mokrane, M.; Scholze, F.; Ulrich, R.; Pampel, H.: re3data and an Ecosystem of Research Data Repositories. 2016 World Library and Information Congress. 82nd IFLA General Conference and Assembly. Columbus, Ohio, 08.08.2016.

Pampel, H.; Vierkant, P.: re3data - Registry of Research Data Repositories. RDA-DE-Trainings-Workshop-2016. Hamburg, 25.05.2016. FolSlidesien: [Slideshare](http://de.slideshare.net/heinzpampel/re3data-registry-of-research-data-repositories).

Pampel, H.; Vierkant, P.; Elger, K.; Bertelmann, R.; Witt, M.; Schirmbacher, P.; Rücknagel, J.; Kindling, M.; Scholze, F.; Ulrich, R.: re3data.org - a global registry of research data repositories. EGU General Assembly 2016. Vienna, 21.04.2016. (Geophysical Research Abstracts, Vol. 18, EGU2016-16765, 2016.) Abstract: [PDF](http://meetingorganizer.copernicus.org/EGU2016/EGU2016-16765.pdf). Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1504148).

Pampel, H.: Open-Access-Gold im Sinne der Wissenschaft gestalten! Workshop des GeSIG Netzwerk Fachinformation. Universität Stuttgart, 12.04.2016. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/openaccessgold-im-sinne-der-wissenschaft-gestalten), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1503986).

Pampel, H.: ORCID DE – Initiative zur Förderung von ORCID in Deutschland. 6. Bibliothekskongress. Leipzig, 15.03.2016. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/orcid-de-initiative-zur-frderung-von-orcid-in-deutschland), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1503984).

Session: Forschungsdaten managen I. 6. Bibliothekskongress. Leipzig, 14.03.2016. Moderation.

Pampel, H.: Auf dem Weg zu Open Science – Strategien und Erfahrungen am GFZ. Fachhochschule Potsdam. Potsdam, 21.01.2016. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/auf-dem-weg-zu-open-science-strategien-und-erfahrungen-am-gfz), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1453909).

Pampel, H.: Forschungsdaten-Repositorien. Vorlesung. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 16.12.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/forschungsdatenrepositorien), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1504131).

Pampel, H. Kindling, M., Scholze, F.: re3data.org – Registry of Research Data Repositories. RDA-Deutschland-Treffen 2015. Potsdam, 26.11.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/re3dataorg-registry-of-research-data-repositories).

Panel Discussion: "Mit dem Bereitstellen fängt es erst an … Die Bedeutung der Postpublikation". #RKB15-Konferenz. Carl Friedrich von Siemens Stiftung, München. 09.10.2015. [Diskussion](http://rkb.hypotheses.org/rkb15-programm).

Pampel, H.: Open-Access-Gold - Einführung anhand der „Positionen zur Schaffung eines wissenschaftsadäquaten Open-Access-Publikationsmarktes“. Open-Access-Tage 2015. Universität Zürich, 08.09.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/openaccessgold-einfhrung-anhand-der-positionen-zur-schaffung-eines-wissenschaftsadquaten-openaccesspublikationsmarktes), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1469919).

Vierkant, P.; Zielke, D.; Müller, U.; Pampel, H.; Scholze, F.: DINI Certificate 2013 for Open Access Repositories and Publication Services. Open-Access-Tage 2015. Universität Zürich, 07.09.2015. Poster: [PDF](http://doi.org/10.5281/zenodo.30780).

Vierkant, P.; Pampel, H.; Kindling, M.; Witt, M.; Scholze, F.: re3data.org – Registry of Research Data Repositories. Open-Access-Tage 2015. Universität Zürich, 07.09.2015. Poster: [PDF](http://doi.org/10.5281/zenodo.30782).

Scholze, F.; Pampel, V.; Vierkant, P.: Making Research Data Repositories Visible – The re3data.org Registry. 44th LIBER Annual Conference. London, 25.06.2015. Slides: [Slideshare](http://de.slideshare.net/kitbib/scholze-liber-20150625final).

Scholze, F.; Pampel, H.; Witt, M.; Vierkant, P.; Kindling, M.: Current Status and Future Plans of re3data.org - Registry of Research Data Repositories. CERN Workshop on Innovations in Scholarly Communication (OAI9). University of Geneva. Geneva, 18.06.2015. [Poster](https://indico.cern.ch/event/332370/session/9/contribution/45).

Vierkant, P.; Müller, U.; Zielke, D.; Scholze, F.; Pampel, H.: DINI Certificate 2013 for Open Access Repositories and Publication Services. CERN Workshop on Innovations in Scholarly Communication (OAI9). University of Geneva. Geneva, 18.06.2015. [Poster](https://indico.cern.ch/event/332370/session/9/contribution/47).

Pampel, H.; Elger, K.: Forschungsergebnisse dauerhaft zugänglich machen - Strategien und Erfahrungen am GFZ. e-Infrastructures Austria Workshop. Österreichische Akademie der Wissenschaften. Wien, 08.06.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/forschungsergebnisse-dauerhaft-zuganglich-machen), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1504062).

Kindling, M.; Pampel, H.; Scholze, F.: Stand und Perspektive des globalen Verzeichnisses von Forschungsdaten-Repositorien re3data.org. 8. DFN-Forum Kommunikationstechnologien. Lübeck, 08.06.2015. Slides: [Slideshare](http://de.slideshare.net/MaxiKindling/stand-und-perspektive-des-globalen-verzeichnisses-von-forschungsdatenrepositorien-re3dataorg) , [PDF](http://www.dfn2015-luebeck.de/tl_files/dfn_tagung_2015/Dokumente/DFN-Forum2015-Kindling-Re3data_org.pdf).

Pampel, H.; Scholze, F.: Vom Projekt zum Service – zur Rolle von re3data.org in der Forschungsdateninfrastruktur. 104. Deutscher Bibliothekartag. Nürnberg, 29.05.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/vom-projekt-zum-service-zur-rolle-von-re3dataorg-in-der-forschungsdateninfrastruktur), [PDF](http://nbn-resolving.de/urn/resolver.pl?urn:nbn:de:0290-opus4-17739).

Session: Forschungsdatenmanagement I. 104. Deutscher Bibliothekartag. Nürnberg, 28.05.2015. Moderation.

Pampel, H.: Open Science in wissenschaftlichen Einrichtungen. GEWISS Dialogforen Citizen Science "Datenqualität, Datenmanagement und rechtliche Aspekte in Citizen Science". Hamburg, 04.05.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-science-in-wissenschaftlichen-einrichtungen), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1504097).

Hammitzsch, M., Fritzsch, B., Reusser, D., Brembs, B., Deinzer, G., Loewe, P., Fenner, M., Van Edig, X., Bertelmann, R., Pampel, H., Klump, J., Wächter, J.: Publishing Platform for Scientific Software – Lessons Learned. EGU General Assembly 2015. Vienna, 14.04.2015. (Geophysical Research Abstracts, Vol. 17, EGU2015-13068, 2015.) Abstract: [PDF](http://meetingorganizer.copernicus.org/EGU2015/EGU2015-13068.pdf). Poster: [PDF](http://hdl.handle.net/10013/epic.45569).

Pampel, H., Scholze, F., Vierkant, P., Bertelmann, R.: re3data.org – A Registry of Research Data Repositories. Large-Scale Data Management and Analysis (LSDMA) Community Forum 2015. Berlin, 26.03.2015. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:979940).

Pampel, H.: Open Science - Handlungsfeld für Informationsinfrastrukturen. Fachhochschule Potsdam. Potsdam, 22.01.2015. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-science-handlungsfeld-fur-informationsinfrastrukturen), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1274112).

Hammitzsch, M,; Klump, J.; Fenner, M.; Pampel, H.; Bertelmann, R.; Brembs, B.; Deinzer, G.; Reusser, D.; Fritzsch, B.: Löwe, P.; Wächter, J.: Scientific Software – Publish, Cite, and get Credit for your Code. AGU Fall Meeting. San Francisco, 16.12.2014. Abstract: [PDF](http://hdl.handle.net/10013/epic.45570).

Scholze, F.; Pampel, H.; Vierkant, P.; Bertelmann, R.: Making Research Data Repositories Visible – The re3data.org Registry. 5th International Symposium on Information Management in a Changing World. Antalya, Turkey, 25.11.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/making-research-data-repositories-visible-the-re3dataorg-registry), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1033899).

Pampel, H., Vierkant, P., Scholze, F., Bertelmann, R.: re3data.org - a Registry of Research Data Repositories. Research Data Alliance (RDA) Germany Meeting. Potsdam, 21.11.2014 . Slides: [Slideshare](http://de.slideshare.net/heinzpampel/re3dataorg-a-registry-of-research-data-repositories), [PDF](http://admin.icordi.eu/Repository/document/RDA_DE_Nov2014/rda_d_34_pampel.pdf).

Witt, M.; Pampel, H.; Zhang, X. ; Wang. H.: re3data: A Global Registry of Research Data Repositories. 2014 Chinese Institutional Repository Conference, China Knowledge Symposium Agency, Xiamen City, 05.11.2014.

Anhörung: "Open Access im Hochschulgesetz verankern - Wissenschaftlerinnen und Wissenschaftler stärken." Ausschuss für Innovation, Wissenschaft und Forschung des Landtags Nordrhein-Westfalen. Düsseldorf, 29.10.2014. [Stellungnahme](http://www.landtag.nrw.de/portal/WWW/Webmaster/GB_I/I.1/aktuelle_drucksachen/aktuelle_Dokumente.jsp?docTyp=ST&wp=15&dokNum=Drs+16%2F5476&searchDru=suchen).

Pampel, H., Vierkant, P., Scholze, F., Bertelmann, R., Kindling, M. re3data.org - A Registry of Research Data Repositories. Veranstaltung "Open-Access-Strategie für Berlin". Berlin, 13.10.2014. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:638890).

Bertelmann, R.; Elger, K.; Pampel, H.: Forschungsdateninfrastrukturen am Deutschen GeoForschungsZentrum GFZ ‐ Policies und Dienstleistungen. 1. DINI/nestor-Workshop "Institutionelle Forschungsdaten-Policies und strategische Planung des Forschungsdatenmanagements". Berlin, 02.10.2014. Slides: [PDF](http://www.forschungsdaten.org/index.php/Datei:Bertelmann-Foda_Policies_GFZ.pdf).

Pampel, H.: Open-Access-Publikationsfonds – strategisches Instrument der Informationsinfrastruktur. \[sic!\] Jülich – Helmholtz Open Science Workshop 2014. Jülich, 30.09.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/openaccesspublikationsfonds-strategisches-instrument-der-informationsinfrastruktur), [PDF](http://hdl.handle.net/2128/8002).

Pampel, H.: Zugänglichkeit von digitalen Forschungsdaten – Strategien und Werkzeuge. Auftaktveranstaltung GEWISS Dialogforen Citizen Science. Leipzig, 18.09.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/zugnglichkeit-von-digitalen-forschungsdaten-strategien-und-werkzeuge), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1274106).

Session: Offene Infrastrukturen für offene Forschungsdaten. Open-Access-Tage 2014. Köln, 09.09.2014. [Moderation](http://open-access.net/de/aktivitaeten/open_access_tage/programm/abstracts/#c4859).

Pampel, H.: Tools für das Management von Forschungsdaten. Workshop „Wege in die Köpfe“ des DFG-Projekts „EWIG - Entwicklung von Workflowkomponenten für die Langzeitarchivierung von Forschungsdaten in den Geowissenschaften“. Berlin, 03.07.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/tools-fr-das-management-von-forschungsdaten),[PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1274108).

Pampel, H.: Forschungsdaten-Repositorien. Vorlesung. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 12.06.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/vorlesung-forschungsdatenrepositorien-ss14), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1274110).

Pampel, H.: re3data.org – Stand und Perspektive. 103. Deutscher Bibliothekartag, Bremen, 04.06.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/re3dataorg-stand-und-perspektive), [PDF](http://nbn-resolving.de/urn:nbn:de:0290-opus-15756).

Pampel, H.; Kindling, M.; Scholze, F.: Rolle und Perspektive von re3data.org bei der Förderung von Open Science. 103. Deutscher Bibliothekartag, Bremen, 04.06.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/re3data-orgopensciencebibtag14), [PDF](http://nbn-resolving.de/urn:nbn:de:0290-opus-15741).

Hammitzsch, M.; Löwe, P.; Klump, J.; Reusser, D.; Fritzsch, B.; Brembs, B.; Deinzer, G.; Bertelmann, R.; Pampel, H.; Fenner, M.; Wächter, J.: SciForge - Publication and citation of scientific software with persistent identifiers. EGU General Assembly 2014. OSGeo Townhall Meeting. Wien, 29.04.2014. Slides: [Slideshare](http://de.slideshare.net/MartinHammitzsch/sciforge-egu2014os-geotownhallmeeting).

Pampel, H.: Open Access und die wissenschaftliche Community. 131. Kongress der Deutschen Gesellschaft für Chirurgie. Berlin, 26.03.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-access-und-die-wissenschaftliche-community), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:1079893).

Pampel, H.: Open Science - Chancen und Herausforderungen für Informationsinfrastrukturen. Fachhochschule Potsdam. Potsdam, 16.01.2014. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-scienceinformationsinfrastrukturen).

Kindling, M., Klump, J., Scholze, F., Pampel, H., Vierkant, P.: re3data.org - A Registry of Research Data Repositories. „Vernetzung – Austausch – Nachnutzung“. Workshop zur Präsentation von Projekten aus dem Förderbereich Informationsmanagement der Deutsche Forschungsgemeinschaft (DFG). Bonn, 16.-17.12.2013. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:309393).

Anhörung: "Open Access – Freier Zugang zu wissenschaftlichen Werken – Stand der Initiativen der Hochschulen, der Forschungszentren und des Landes Berlin zu den Handlungsfeldern technische Infrastruktur, institutionelle Koordination und rechtliche Rahmenbedingungen." Ausschuss für Wissenschaft des Abgeordnetenhaus von Berlin. Berlin, 04.12.2013.

Pampel, H.: Informationsinfrastrukturen für Open Science. PubMan Days 2013. Max-Planck-Gesellschaft. München, 23.10.2013. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/informationsinfrastrukturen-fr-open-science).

Pampel, H.: Open Access - Offener Zugang zu wissenschaftlichem Wissen. Cologne Commons Conference 2013. Universität zu Köln, 17.10.2013. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-access-offener-zugang-zu-wissenschaftlichem-wissen).

Session: Rechtliche Aspekte des Open Access. Open-Access-Tage 2013. Staats- und Universitätsbibliothek Hamburg und ZBW - Leibniz-Informationszentrum Wirtschaft. Hamburg, 10.10.2013. Moderation. [Abstract](http://open-access.net/de/aktivitaeten/open_access_tage/programm/sessions/#c3970), [Video](http://youtu.be/DmIh_orxRX8).

Kindling, M.; Scholze, F.; Pampel, H.; Vierkant, P.: re3data.org - A Registry of Research Data Repositories. CERN Workshop on Innovations in Scholarly Communication (OAI8). Geneva, 20.06.2013. Poster: [Abstract](https://indico.cern.ch/contributionDisplay.py?contribId=60&sessionId=7&confId=211600), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:309393).

Pampel, H.: Forschungsdaten Repositorien. Humboldt-Universität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft (IBI). Berlin, 06.06.2013. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/forschungsdaten-repositorien).

Pampel, H. & Bertelmann, R.: Von Subskription zu Open Access. Transformationsprozesse in der Helmholtz-Gemeinschaft. 5. Kongress Bibliothek & Information Deutschland. Leipzig, 11.03.2013. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/von-subskription-zu-open-access-17106248), [PDF](http://nbn-resolving.de/urn:nbn:de:0290-opus-13795).

Pampel, H. Forschungdaten-Repositorien - Stand und Perspektive zu Open Access. 5. Kongress Bibliothek & Information Deutschland. Leipzig, 11.03.2013. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/re3data-orgbid13), [PDF](http://nbn-resolving.de/urn:nbn:de:0290-opus-13804).

Pampel, H.: Open Access - Umsetzungsstrategien und urheberrechtliche Aspekte. Zentrum für Bibliotheks- und Informationswissenschaftliche Weiterbildung der Fachhochschule Köln. Köln, 19.02.2013. Seminar. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/fh-koelnopenaccessseminar), [PDF](360884).

Pampel, H.: Transformation der Wissenschaftskommunikation. Von Subskription zu Open Access. Hochschule für Technik und Wirtschaft (HTW). Chur, 28.11.2012. Seminar. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/von-subskription-zu-open-access), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:360886).

Workshop: Urheberrecht und Wissenschaft im digitalen Zeitalter. 2. Netzpolitischer Kongress der Bündnis 90/Die Grünen Bundestagsfraktion. Berlin, 20.10.2012. [Diskussion](http://www.gruene-bundestag.de/fraktion/netzpolitischer-kongress_ID_4385426/7-urheberrecht-und-wissenschaft-im-digitalen-zeitalter_ID_4385582.html).

Pampel, H.: Quality Assurance of Research Data: Perspectives of Scientist, Infrastructure Providers, and Publishers. APARSEN Satellite Session der Open-Access-Tage 2012, Wien, 27.09.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/quality-assurance-of-research-data), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:246565).

Pampel, H.: Forschungsdaten-Repositorien - Typen, Herausforderungen und Perspektiven. Open-Access-Tage 2012, Wien, 26.09.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/forschungsdaten-repositorienoat12), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:246567).

Kindling, M.; Vierkant, P.; Pampel, H.: Making Data Repositories Visible: A Work Report from the re3data.org Project. 7th International Conference on Open Repositories. Edinburgh, 10.07.2012. Poster: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:246569).

Pampel, H.: Forschungsdaten-Repositorien. Informationsinfrastrukturen für nachnutzbare Forschungsdaten. 12. Oracle Bibliotheken Summit, Bonn, 21.06.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/forschungsdatenrepositorien-informationsinfrastrukturen-fur-nachnutzbare-forschungsdaten), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:245340).

Pampel, H.; Kindling, M.: Repositorien für Forschungsdaten - Infrastrukturen für die digitale Wissenschaft. 101. Deutscher Bibliothekartag, Hamburg, 24.05.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/pampel-kindling-repositorien-fr-forschungsdaten-infrastrukturen-fr-die-digitale-wissenschaft), [PDF](http://nbn-resolving.de/urn:nbn:de:0290-opus-11910).

Pampel, H.: „Data Policies“ - Zuckerbrot oder Peitsche?. Experten‐Workshop des DFG-Projektes Rahmenbedingungen einer disziplinübergreifenden Forschungsdateninfrastruktur. Potsdam, 17.04.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/data-policies-zuckerbrot-oder-peitsche), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:245140).

Pampel, H.: Rahmenbedingungen der Transformation. Von Subskription zu Open Access. 6. Konsortialtag des Friedrich-Althoff-Konsortium. Berlin, 16.04.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/2012-0416-fak12), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:245138).

Pampel, H.: Open Access. BI-Akademie der Hochschule der Medien (HdM). Stuttgart, 07.03.2012. Seminar.

Pampel, H.: Neue Wege im Umgang mit Forschungsdaten. Chancen und Herausforderungen für Wissenschaft und Infrastruktur. BW-eLabs Abschlussveranstaltung. Stuttgart, 23.01.2012. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/neue-wege-im-umgang-mit-forschungsdaten), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:245109).

Session: Wissenschaftliches Publizieren - Auswirkungen des Web 2.0 auf Publikationsformen und Qualitätsstandards. AcademiaNet Dialogforum. Berlin, 02.11.2011. Moderation.

Pampel, H.: *„*Data Sharing“ zwischen Wunsch und Wirklichkeit. Open-Access-Tage 2011. Regensburg, 05.10.2011. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/data-sharing-zwischen-wunsch-und-wirklichkeit), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:244046).

Pampel, H.: Open-Access-Publikationsgebühren: Erfahrungen und Diskussionen in der Helmholtz-­Gemeinschaft. Open-Access-Tage 2011. Regensburg, 04.10.2011. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:244052).

Pampel, H.: Offener Zugang zu Forschungsdaten - Einführung. Open-Access-Tage 2011. Regensburg, 04.10.2011. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:244050).

Pampel, H.: Forschungsdaten organisieren - Herausforderungen für Wissenschaft und Infrastruktur. 12. Jahrestreffen des Arbeitskreises Bibliotheken und Informationseinrichtungen der Leibniz-Gemeinschaft. Dortmund, 30.09.2011.\

Kaden, B.; Kindling, M.; Pampel, H.: Information und Gesellschaft. Zur politischen Dimension der Informationswissenschaft. Informare 2011. Berlin, 03.05.2011. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/information-und-gesellschaft).

Pampel, H.: Repositories, CTAs and the question of gratis vs. libre. IUWIS Workshop, Osnabrück, 02.03.2011. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/repositories-ctas-and-the-question-of-gratis-vs-libre), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:243426).

Pampel, H.: On the gold road to OA. SOAP Symposium. Berlin, 13.01.2011. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/on-the-gold-road-to-oa), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:243428).

Heller, L.; Pampel, H.: Konzeptstudie: Die informationswissenschaftliche Zeitschrift der Zukunft. 1. DGI-Konferenz, 62. DGI Jahrestagung. Frankfurt am Main, 07.10.2010. Slides: [Slideshare](http://www.slideshare.net/lambo/lambert-heller-heinz-pampel-konzeptstudie-die-informationswissenschaftliche-zeitschrift-der-zukunft).

Pampel, H.: Offener Zugang zu Forschungsdaten - Einführung. Open-Access-Tage 2010. Göttingen, 04.10.2010. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/offener-zugang-zu-forschungsdaten-einfhrung-5345352).

Pampel, H.: Open Access: Von der Zugänglichkeit zur Nachnutzung. Digitale Wissenschaft 2010. Köln, 20.09.2010. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/open-access-von-der-zugnglichkeit-zur-nachnutzung). [Video](http://www.scivee.tv/node/24980).

Pampel, H.: Umgang mit digitalen Forschungsdaten - Initiativen in Deutschland. Sitzung der AGEP der Humboldt-Universität zu Berlin. Berlin, 25.06.2010. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/2010-0622-huagepfinalverffentlicht), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:240939).

Pampel, H.: Umgang mit Forschungsdaten - Perspektiven und Herausforderungen. XXXIII. Librarian Meeting of the Max Planck Society. Göttingen, 27.04.2010. Slides: [Slideshare](http://de.slideshare.net/heinzpampel/umgang-mit-forschungsdaten-perspektiven-und-herausforderungen), [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:240515).

Pampel, H.: Open Access - Wissenschaftspolitische Relevanz und Positionen. Open Access Week 2009 am Deutschen GeoForschungsZentrum GFZ. Potsdam, 23.10.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239518).

Pampel, H.: Open Access - Relevanz, Diskussion und Perspektiven. Open Access Week 2009 an der Universität Greifswald. Greifswald 21.10.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239508). [Video](http://blip.tv/file/3164090).

Dallmeier-Tiessen, S.; Pampel, H.: Workshop Open Access zu Forschungsdaten. Open-Access-Tage 2009. Konstanz, 08.10.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239514).

Dallmeier-Tiessen, S.; Pampel, H.: Open Access in der Helmholtz-Gemeinschaft. Open-Access-Tage 2009. Konstanz, 07.10.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239516).

Pampel, H.: Das DINI-Positionspapier „Forschungsdaten“ im nationalen und internationalen Kontext. DINI-Jahrestagung 2009. Kassel, 30.09.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239510). [Video](http://www.uni-kassel.de/educampus/HRZ/DINI2009/w090930_1610_Pampel/090930_1610_Pampel.html).

Pampel, H.: Open Access in der Helmholtz-Gemeinschaft: Status und Perspektiven . ASpB-Tagung 2009. Karlsruhe, 23.09.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:239512).

Pampel, H.: Open Access Week 2009 - Konzept und Umsetzung. Vernetzungstage 2009. Stuttgart, 24.06.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:238867).

Pampel, H.; Bertelmann, R.; Hobohm, H.-C.: Data Librarianship - Rollen, Aufgaben, Kompetenzen. 98. Deutscher Bibliothekartag. Erfurt, 05.06.2009. Slides: [PDF](http://nbn-resolving.de/urn/resolver.pl?urn:nbn:de:0290-opus-6985).

Pampel, H.: Open Access in der Helmholtz-Gemeinschaft. 2. oa-net-workshop. Hamburg, 26.01.2009. Slides: [PDF](http://open-access.net/fileadmin/oa-net-work/workshop2/oa-net-workshop-HH2009-VorstellungHelmholtz.pdf).

Pampel, H.; Hübner, A.: Die Aktivitäten der AG Open Access in der Allianz der deutschen Wissenschaftsorganisationen / Open Access Week 2009. 2. oa-net-workshop. Hamburg, 26.01.2009. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:238593).

Dallmeier-Tiessen, S.; Pampel, H.: Herausforderung Forschungsdaten. 9. DINI-Jahrestagung; Öffentliche Sitzung der DINI-Arbeitsgruppe Elektronisches Publizieren. Hamburg, 23.10.2008. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:237704).

Pampel, H.; Hübner, A.: Open Access in the Helmholtz Association. Berlin 6 Open Access Conference. Düsseldorf, 12.11.2008. [Poster](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:237881).

Pampel, H.; Bertelmann, R.; Hübner, A.: Bibliotheken und Forschungsdaten: Perspektiven. 97. Deutscher Bibliothekartag. Mannheim, 04.06.2008. Slides: [PDF](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:236938).

Hübner, A.; Pampel, H.: Das Helmholtz Open Access Projekt - Open Access im Dienst der Wissenschaft. DFG/DINI Workshop 'Förderung der wissenschaftlichen Informationslandschaft in Deutschland' - Chancen und Strategien beim Aufbau vernetzter Repositorien. Berlin, 26.-27.02.2008. [Poster](http://gfzpublic.gfz-potsdam.de/pubman/item/escidoc:236572).

Pampel, H.: Universitätsverlage in Deutschland. Dienstleister für die Wissenschaft. Zusammenfassung einer Bestandsaufnahme. 10. Internationales Symposium für Informationswissenschaft. Köln, 31.05.2007. [Abstract](http://www.iuk2007.de/fileadmin/user_upload/Abstracts.htm#pampel).
