---
title: "Working Groups"
---

---
title: "Working Groups"
---

## Associations and Institutions

### Ongoing

2025– Member of the Task Force Open Science of Circle U.  

2024– Member of the Advisory Board of the Rogue Scholar Science Blog Archive  

2024– Co-Chair of the Interest Group “Advancing Scientific Publishing” [Interessensgruppe „Weiterentwicklung des wissenschaftlichen Publizierens”] in the focus area “Digitality in Science” [Schwerpunkt „Digitalität in der Wissenschaft”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2024– Member of the Interest Group “Reputation and Incentives” [Interessensgruppe „Reputation und Anreize”] in the focus area “Digitality in Science” [Schwerpunkt „Digitalität in der Wissenschaft”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2024– Member of the Working Group “Infrastructure” in the CERN/NASA Initiative “Accelerating the Adoption of Open Science”  

2024– Member of the Section “Common Infrastructures” of the National Research Data Infrastructure (NFDI) [Nationale Forschungsdateninfrastruktur (NFDI)]  

### Finished

2024 Member of the Task Force on Artificial Intelligence and Licensing [Task Force Künstliche Intelligenz und Lizenzen] within the focus area “Digitality in Science” [Schwerpunkt „Digitalität in der Wissenschaft”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2021–2025 Member of the Task Force for Measure 4 (“Open Access and Research Assessment”) [Task Force Maßnahme 4 „Open Access und Forschungsbewertung”] of the Open Access Strategy [Open-Access-Strategie] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2018–2023 Member of the Scientific Publication System Working Group [Arbeitsgruppe Wissenschaftliches Publikationssystem] in the Priority Initiative “Digital Information” [Schwerpunktinitiative „Digitale Information”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2018–2019 Member of the Open Access Strategy Network [Netzwerk Open-Access-Strategie] of the State of Brandenburg [Land Brandenburg]  

2015–2016 Member of the Advisory Board of RADAR – Research Data Repository [Beirat von RADAR – Research Data Repositorium]  

2014–2022 Member of the Executive Board [Vorstand] of the German Initiative for Network Information (DINI) [Deutsche Initiative für Netzwerkinformation (DINI)]  

2014–2018 Member of the Affiliate Team of Creative Commons Germany [Affiliate Team von Creative Commons Deutschland]  

2013–2015 Co-Chair of the Ad-hoc Working Group Open Access Gold [Ad-hoc Arbeitsgruppe Open Access Gold] in the Priority Initiative “Digital Information” [Schwerpunktinitiative „Digitale Information”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2010–2011 Member of the Commission for the Future of Information Infrastructure (KII) [Kommission Zukunft der Informationsinfrastruktur (KII)] on behalf of the Joint Science Conference of the Federal Government and the Länder (GWK) [Gemeinsame Wissenschaftskonferenz des Bundes und der Länder (GWK)]  

2010–2011 Member of the Working Group on Publication Models and Economics [Arbeitskreis Publikationsmodelle und -ökonomie] of the German Society for Information Science and Information Practice (DGI) [Deutsche Gesellschaft für Informationswissenschaft und Informationspraxis (DGI)]  

2009–2017 Member of the Open Access Working Group [Arbeitsgruppe Open Access] in the Priority Initiative “Digital Information” [Schwerpunktinitiative „Digitale Information”] of the Alliance of German Science Organizations [Allianz der deutschen Wissenschaftsorganisationen]  

2008–2020 Member of the Electronic Publishing Working Group [Arbeitsgruppe Elektronisches Publizieren] in the German Initiative for Network Information (DINI) [Deutsche Initiative für Netzwerkinformation (DINI)]  

2008–2014 Member of the Multipliers Network “oa-net-work” [Multiplikatoren-Netzwerk oa-net-work] of the information platform open-access.net [Informationsplattform open-access.net]  

## Editorial Boards

Member of the Editorial Board at Nature Scientific Data (since 2025)  

Community Reviewer for Scholarly Communications at Frontiers in Research Metrics and Analytics (since 2025)  

## Conferences and Workshops

### Program Committees

Conference “Scholar-led Open-Access Publishing” [Wissenschaftsgeleitetes Open-Access-Publizieren]. Humboldt-Universität zu Berlin, September 26, 2023. Conference Chair  

Open Science Conference 2021. Online, February 17–19, 2021. Review Board  

Open Science Conference 2020. Berlin, March 11–12, 2020. Review Board  

WissKom2016. Forschungszentrum Jülich, June 14–16, 2016. Program Committee  

Open Access Days 2014 [Open-Access-Tage 2014]. Fachhochschule Köln, September 8–9, 2014. Program Committee  

Open Access Days 2013 [Open-Access-Tage 2013]. Staats- und Universitätsbibliothek Hamburg, October 1–2, 2013. Program Committee  

Open Access Days 2012 [Open-Access-Tage 2012]. Universität Wien, September 26–27, 2012. Program Committee  

Open Access Days 2011 [Open-Access-Tage 2011]. Universität Regensburg, October 4–5, 2011. Program Committee  

Open Access Days 2010 [Open-Access-Tage 2010]. Georg-August-Universität Göttingen, October 4–5, 2010. Program Committee  

Open Access Days 2008 [Open-Access-Tage 2008]. Freie Universität Berlin, October 9–10, 2008. Program Committee  

### Workshop and Conference Organization

Workshop “Institutional Repositories and Secondary Publications” [Repositorien und Zweitveröffentlichungen]. Online, January 13, 2025. Co-Organizer  

Workshop “Institutional Repositories and FIS/CRIS” [Repositorien und Forschungsinformationssysteme]. Online, December 11, 2024. Co-Organizer  

Workshop “Infra Wiss Blogs” [Infra Wiss Blogs]. Einstein Center Digital Future (ECDF), December 6, 2024. Co-Organizer  

Workshop “Institutional Repositories and Preprints” [Repositorien und Preprints]. Online, November 13, 2024. Co-Organizer  

Panel Discussion “Open Access Monitoring – Opportunities and Challenges for Open Science” [Open-Access-Monitoring – Chancen und Herausforderungen für Open Science]. (Kick-off Event in the Series Quo vadis Open Science in Berlin and Brandenburg 2024) Online, October 21, 2024. Co-Organizer  

Workshop “Research Data Publications between Dynamism and Persistence” [Forschungsdaten-Publikationen zwischen Dynamik und Persistenz]. Einstein Center Digital Future (ECDF), June 28, 2024. Workshop Chair  

Panel Discussion “Open Infrastructures for Open Science” [Offene Infrastrukturen für Open Science]. Online, February 19, 2024. Co-Organizer  

Workshop “Monitoring Research Data Publications: Status and Perspectives” [Monitoring von Forschungsdaten-Publikationen: Stand und Perspektive]. Online, November 30, 2023. Co-Organizer  

Panel Discussion “Open Access in the Berlin-Brandenburg Region: Achievements and Future Directions” [Open Access in der Region Berlin-Brandenburg: Was wurde erreicht und wo geht es hin?]. (Kick-off Event in the Series Quo vadis Open Science in Berlin and Brandenburg 2023) Zuse Institute Berlin (ZIB), October 24, 2023. Co-Organizer  

Edit-a-thon “Diversity in Wikipedia Entries on Library and Information Science” [Diversität in Wikipedia-Beiträgen zur Bibliotheks- und Informationswissenschaft]. Einstein Center Digital Future (ECDF), October 6, 2023. Organizer  

Panel Discussion “Berlin Goes Open Research” [Berlin goes Open Research]. Freie Universität zu Berlin, May 4, 2023. Co-Organizer  

Workshop “ORCID DE – ORCID in Publication and Information Infrastructures” [ORCID in Publikations- und Informationsinfrastrukturen]. Online, June 2, 2021. Co-Organizer  

Workshop “ORCID DE – Organization Identifiers” [Organisationsidentifikatoren]. Online, December 2, 2020. Co-Organizer  

Workshop “ORCID DE – Implementation” [ORCID-Implementierung]. German National Library, September 7, 2017. Co-Organizer  

Workshop “Access to and Reuse of Research Software” [Zugang zu und Nachnutzung von Forschungssoftware]. HZDR – Helmholtz-Zentrum Dresden-Rossendorf, November 22–23, 2016. Co-Organizer  

Workshop “ORCID DE – Outreach” [ORCID Outreach]. GFZ Helmholtz Centre for Geosciences, October 25, 2016. Co-Organizer  

Symposium “Research Data Infrastructures (FDI 2013)” [Forschungsdaten-Infrastrukturen (FDI 2013)]. GFZ Helmholtz Centre for Geosciences, January 22, 2013. Co-Organizer  

Panel Discussion “Open Science – Opportunities and Challenges of Digital Science” [Open Science – Chancen und Herausforderungen der digitalen Wissenschaft]. Humboldt-Universität zu Berlin, October 23, 2012. Co-Organizer  

Workshop “Author Identification” [Autorenidentifikation]. Humboldt-Universität zu Berlin, October 15, 2012. Co-Organizer  

Conference InfoCamp 2012 [InfoCamp 2012]. University of Applied Sciences HTW Chur, September 7–8, 2012. Co-Organizer  

Workshop “Repositories – Practice and Vision” [Repositorien – Praxis und Vision]. Humboldt-Universität zu Berlin, November 30 – December 1, 2010. Co-Organizer  

International Open Access Week [Internationale Open-Access-Woche]. October 19–23, 2009. Member of the German Coordination Committee  

Workshop “Umgang mit Forschungsdaten” [Umgang mit Forschungsdaten]. Alfred Wegener Institute (AWI), September 18–19, 2008. Co-Organizer  
